services:
 db:
  image: postgres:15-alpine
  container_name: postgres_dev_db
  restart: always
  environment:
    POSTGRES_DB: prueba_final
    POSTGRES_USER: user_dev
    POSTGRES_PASSWORD: dev_password
  expose:
    - 5432
  volumes:
    - postgres_data:/var/lib/postgresql/data
  networks: 
    - dokploy-network

 app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: prueba_final_talentotech
    expose:
      - 8080
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/prueba_final
      SPRING_DATASOURCE_USERNAME: user_dev
      SPRING_DATASOURCE_PASSWORD: dev_password
    volumes:
      - .:/app
    entrypoint: ["./mvnw", "spring-boot:run"]
    networks:
      - dokploy-network

volumes:
  postgres_data:

networks: 
  dokploy-network: